### ISSUE TITLE
Overall design change

### ISSUE THREAD

**Issue by msdio** [msdio/stackticon#65]
## 📚 Tasks
overall design change

- [x] setting colors
- [ ] setting shadow

## ✔ Checklists

- [x] main page @msdio 
- [x] common layout @msdio 
- [x] header @msdio 
- [x] background select page @msdio 
- [x] result page @msdio
